### ISSUE TITLE
Please specify version

### ISSUE THREAD

**Issue by leonardo0014** [svalouch/python-rctclient#10]
Hello

what was published here is great.
I only have one request: Please could you please add to the scripts for the InfluxDB for which version it was written? In the meantime there are 1.x and 2.x with gradations and unfortunately you have changed the syntax for the 2.x ...

thanks

**Comment by svalouch** [comment]
Hi Leonardo, that's a good idea! I've added hints to the tool and the documentation regarding the version. While at it, I noticed that InfluxDB 2.x can natively read CSV, so I've removed the `--no-header` option from `timeseries2csv.py` and added a `--header-format` option instead that can prepend a header suitable for InfluxDB 2.x' `influx write` command and documented it. So with InfluxDB 2.x, `csv2influxdb.py` is no longer required.
