### ISSUE TITLE
upgrade to version 0.0.4

### ISSUE THREAD

**Issue by Pythonaire** [svalouch/python-rctclient#27]
Tried to upgrade the version from 0.0.3 to 0.0.4 but failed.
```
pip install -U rctclient --upgrade
```
gives version 0.0.3

```
pip install -U rctclient==0.0.4
```
gives: ERROR: Could not find a version that satisfies the requirement rctclient==0.0.4 (from versions: 0.0.1, 0.0.2, 0.0.3)

**Comment by amokinside** [comment]
I have the same problem....

Is an update from 0.0.3 to 0.04 possible? If yes how?

**Comment by weltenwort** [comment]
Until https://github.com/svalouch/python-rctclient/releases/tag/v0.0.4 has been published to pypi you could use `pip install git+https://github.com/svalouch/python-rctclient@v0.0.4` to install directly from the repo.
