### ISSUE TITLE
Release a new version with recent fixes

### ISSUE THREAD

**Issue by weltenwort** [svalouch/python-rctclient#3]
## :information_source: Summary

Release a new version of this library for easy consumption.

## :mag: Background

Thank you very much for this library.

I'm trying to use it in a custom Home Assistant integration and would like to make use of the recent fixes and features you implemented since releasing 0.0.1. I could use `main` from GitHub, of course, but a proper release would be even better.

**Comment by svalouch** [comment]
Good idea and thanks for reminding me! I want to do some more testing of recent changes but I should have everything ready in the next few days.

**Comment by svalouch** [comment]
Release has been created and uploaded to pypi :tada:
